import type { Product } from './types';

/** The bundled entries pick their silhouette from their category. */
type SeedProduct = Omit<Product, 'artShape'>;

/**
 * The bundled catalog. It is the seed source for Postgres (`prisma/seed.ts`)
 * and the read-only fallback the site serves when DATABASE_URL is not set, so
 * the storefront always renders — locally, in preview, and in CI.
 *
 * Swap `imageUrl` for your own photo URLs as you shoot them. Anything left null
 * renders the generated artwork instead of a broken image.
 */
export const CATALOG: Product[] = (
  [
  // ---------------------------------------------------------------- cookware
  {
    id: 'seed-cast-iron-casserole',
    slug: 'cast-iron-casserole-24cm',
    name: 'Cast Iron Casserole, 24cm',
    brand: 'Homeware & Co',
    category: 'cookware',
    family: 'cast iron',
    description:
      'Enamelled cast iron that holds a low simmer for hours without scorching. The pot for jollof in bulk, egusi that needs time, and anything you want to finish in the oven. Heavy on purpose — that mass is what keeps the heat steady when you add cold ingredients.',
    specs: [
      '24cm diameter · 4.2 litre capacity',
      'Enamelled cast iron, no seasoning required',
      'Oven safe to 260°C, lid included',
      'Works on gas, electric and induction',
    ],
    care: ['Hand wash with warm soapy water', 'Dry fully before storing', 'Avoid thermal shock — no cold water in a hot pot'],
    inBox: ['24cm casserole', 'Cast iron lid', 'Care leaflet'],
    sizeLabel: '24cm · 4.2L',
    price: 96000,
    compareAt: 125000,
    stock: 14,
    imageUrl: null,
    accent: 'clay',
    featured: true,
    bestseller: true,
    rating: 4.9,
    reviewCount: 186,
  },
  {
    id: 'seed-tri-ply-frying-pan',
    slug: 'tri-ply-frying-pan-28cm',
    name: 'Tri-Ply Frying Pan, 28cm',
    brand: 'Homeware & Co',
    category: 'cookware',
    family: 'stainless steel',
    description:
      'Three bonded layers — steel, aluminium, steel — so the base heats evenly right to the edge instead of hot-spotting in the middle. Gets a proper sear on steak and releases cleanly once it is hot.',
    specs: [
      '28cm · 5mm bonded base',
      '18/10 stainless steel with aluminium core',
      'Riveted stay-cool handle',
      'Oven and induction safe',
    ],
    care: ['Dishwasher safe', 'Preheat before adding oil to stop sticking', 'Bar Keepers Friend restores the shine'],
    inBox: ['28cm frying pan'],
    sizeLabel: '28cm',
    price: 62000,
    compareAt: 78000,
    stock: 22,
    imageUrl: null,
    accent: 'slate',
    featured: true,
    bestseller: true,
    rating: 4.8,
    reviewCount: 141,
  },
  {
    id: 'seed-nonstick-set',
    slug: 'granite-nonstick-set-of-three',
    name: 'Granite Non-Stick Set of Three',
    brand: 'Homeware & Co',
    category: 'cookware',
    family: 'non-stick',
    description:
      'A 20cm, 24cm and 28cm set with a mineral-reinforced coating that survives daily eggs and plantain without flaking. PFOA-free, and the handles stay cool on gas.',
    specs: ['20cm, 24cm and 28cm pans', 'PFOA-free granite coating', 'Forged aluminium body', 'Gas, electric and induction'],
    care: ['Hand wash recommended', 'Wooden or silicone utensils only', 'Never heat empty on high'],
    inBox: ['20cm pan', '24cm pan', '28cm pan'],
    sizeLabel: '3 pans',
    price: 74500,
    compareAt: 95000,
    stock: 19,
    imageUrl: null,
    accent: 'ink',
    featured: false,
    bestseller: true,
    rating: 4.7,
    reviewCount: 208,
  },
  {
    id: 'seed-stockpot',
    slug: 'stainless-stockpot-12l',
    name: 'Stainless Stockpot, 12L',
    brand: 'Homeware & Co',
    category: 'cookware',
    family: 'stainless steel',
    description:
      'The party-size pot. Twelve litres for stock, soup, or cooking rice for a house full of people, with a sandwiched base so the bottom does not catch.',
    specs: ['12 litre capacity', 'Encapsulated base', 'Tempered glass lid', 'Induction compatible'],
    care: ['Dishwasher safe', 'Dry immediately to avoid water marks'],
    inBox: ['12L stockpot', 'Glass lid'],
    sizeLabel: '12L',
    price: 58000,
    compareAt: null,
    stock: 16,
    imageUrl: null,
    accent: 'slate',
    featured: false,
    bestseller: false,
    rating: 4.7,
    reviewCount: 74,
  },

  // ------------------------------------------------------------------ knives
  {
    id: 'seed-chef-knife',
    slug: 'chef-knife-20cm',
    name: "Chef's Knife, 20cm",
    brand: 'Homeware & Co',
    category: 'knives',
    family: 'carbon steel',
    description:
      'German steel at 56 HRC — hard enough to hold an edge through a week of prep, soft enough to sharpen at home without special kit. Full tang, balanced at the bolster so it feels lighter than it is.',
    specs: ['20cm blade · full tang', 'X50CrMoV15 German steel, 56 HRC', 'Triple-riveted pakkawood handle', '15° edge per side'],
    care: ['Hand wash and dry immediately', 'Hone weekly, sharpen twice a year', 'Never leave soaking'],
    inBox: ["20cm chef's knife", 'Blade guard'],
    sizeLabel: '20cm',
    price: 48500,
    compareAt: 62000,
    stock: 27,
    imageUrl: null,
    accent: 'slate',
    featured: true,
    bestseller: true,
    rating: 4.9,
    reviewCount: 233,
  },
  {
    id: 'seed-knife-block-set',
    slug: 'knife-block-set-of-six',
    name: 'Knife Block Set of Six',
    brand: 'Homeware & Co',
    category: 'knives',
    family: 'carbon steel',
    description:
      "Chef's, santoku, bread, carving, paring and utility in an acacia block with a built-in honing steel. The set to buy once when setting up a kitchen.",
    specs: ['6 knives plus honing steel', 'Acacia wood block', 'Full-tang forged blades', 'Dishwasher safe (hand wash advised)'],
    care: ['Hand wash and dry immediately', 'Store in the block, never loose in a drawer'],
    inBox: ['6 knives', 'Honing steel', 'Acacia block'],
    sizeLabel: '6 pieces',
    price: 128000,
    compareAt: 165000,
    stock: 9,
    imageUrl: null,
    accent: 'sand',
    featured: true,
    bestseller: false,
    rating: 4.8,
    reviewCount: 88,
  },
  {
    id: 'seed-end-grain-board',
    slug: 'acacia-end-grain-board',
    name: 'Acacia End-Grain Board',
    brand: 'Homeware & Co',
    category: 'knives',
    family: 'acacia wood',
    description:
      'End-grain construction means the blade slides between wood fibres instead of cutting across them — kinder to your knives and it closes up rather than scarring. Deep juice groove for meat.',
    specs: ['45 × 30 × 4cm', 'End-grain acacia', 'Juice groove and side handles', 'Non-slip feet'],
    care: ['Hand wash only, never submerge', 'Oil monthly with food-safe mineral oil'],
    inBox: ['End-grain board'],
    sizeLabel: '45 × 30cm',
    price: 42000,
    compareAt: null,
    stock: 24,
    imageUrl: null,
    accent: 'sand',
    featured: false,
    bestseller: true,
    rating: 4.9,
    reviewCount: 117,
  },

  // -------------------------------------------------------------- appliances
  {
    id: 'seed-gooseneck-kettle',
    slug: 'gooseneck-electric-kettle',
    name: 'Gooseneck Electric Kettle',
    brand: 'Homeware & Co',
    category: 'appliances',
    family: 'stainless steel',
    description:
      'Variable temperature from 60 to 100°C with a narrow spout for slow, controlled pouring. Made for pour-over coffee and loose-leaf tea, and it holds temperature for 30 minutes.',
    specs: ['1.0 litre · 1200W', 'Variable 60–100°C', '30-minute hold', 'Brushed stainless, cool-touch handle'],
    care: ['Descale monthly with citric acid', 'Wipe exterior with a damp cloth'],
    inBox: ['Kettle', 'Power base', 'Manual'],
    sizeLabel: '1.0L',
    price: 68000,
    compareAt: 85000,
    stock: 18,
    imageUrl: null,
    accent: 'ink',
    featured: true,
    bestseller: true,
    rating: 4.8,
    reviewCount: 164,
  },
  {
    id: 'seed-high-speed-blender',
    slug: 'high-speed-blender-2l',
    name: 'High-Speed Blender, 2L',
    brand: 'Homeware & Co',
    category: 'appliances',
    family: 'appliance',
    description:
      'A 1500W motor with hardened stainless blades — it handles tomatoes and pepper for stew without straining, and crushes ice properly. Two litre shatterproof jug.',
    specs: ['1500W motor', '2 litre BPA-free jug', '6-blade stainless assembly', 'Pulse and 3 speeds'],
    care: ['Blend warm soapy water to self-clean', 'Jug is dishwasher safe, base is not'],
    inBox: ['Motor base', '2L jug', 'Tamper', 'Manual'],
    sizeLabel: '2L · 1500W',
    price: 89000,
    compareAt: 112000,
    stock: 13,
    imageUrl: null,
    accent: 'ink',
    featured: false,
    bestseller: true,
    rating: 4.7,
    reviewCount: 195,
  },
  {
    id: 'seed-toaster',
    slug: 'two-slice-toaster',
    name: 'Two-Slice Toaster',
    brand: 'Homeware & Co',
    category: 'appliances',
    family: 'appliance',
    description:
      'Wide slots that take agege bread and bagels, six browning levels, and a crumb tray that actually slides out. Brushed steel that does not show fingerprints.',
    specs: ['2 extra-wide slots', '6 browning levels', 'Defrost and reheat', 'Removable crumb tray'],
    care: ['Unplug and cool before cleaning', 'Empty the crumb tray weekly'],
    inBox: ['Toaster'],
    sizeLabel: '2 slice',
    price: 39500,
    compareAt: null,
    stock: 21,
    imageUrl: null,
    accent: 'slate',
    featured: false,
    bestseller: false,
    rating: 4.6,
    reviewCount: 82,
  },

  // --------------------------------------------------------------- tableware
  {
    id: 'seed-stoneware-dinner-set',
    slug: 'stoneware-dinner-set-16-piece',
    name: 'Stoneware Dinner Set, 16 Piece',
    brand: 'Homeware & Co',
    category: 'tableware',
    family: 'stoneware',
    description:
      'Service for four in a soft reactive glaze, so no two pieces are quite identical. Stoneware is heavier and far more chip-resistant than earthenware — this is a set for everyday, not the cabinet.',
    specs: ['4 dinner plates, 4 side plates, 4 bowls, 4 mugs', 'Reactive glaze stoneware', 'Dishwasher and microwave safe', 'Stacks flat'],
    care: ['Dishwasher safe', 'Avoid stacking wet to protect the glaze'],
    inBox: ['16 pieces, service for four'],
    sizeLabel: '16 pieces',
    price: 84000,
    compareAt: 108000,
    stock: 17,
    imageUrl: null,
    accent: 'clay',
    featured: true,
    bestseller: true,
    rating: 4.9,
    reviewCount: 172,
  },
  {
    id: 'seed-serving-bowl',
    slug: 'large-serving-bowl',
    name: 'Large Serving Bowl',
    brand: 'Homeware & Co',
    category: 'tableware',
    family: 'stoneware',
    description:
      'A 30cm bowl deep enough for salad for eight or rice for the table. Wide rim so it is easy to carry when full and hot.',
    specs: ['30cm diameter · 3.5L', 'Reactive glaze stoneware', 'Oven safe to 220°C'],
    care: ['Dishwasher safe', 'Not for direct flame'],
    inBox: ['Serving bowl'],
    sizeLabel: '30cm',
    price: 26500,
    compareAt: null,
    stock: 31,
    imageUrl: null,
    accent: 'sage',
    featured: false,
    bestseller: false,
    rating: 4.8,
    reviewCount: 63,
  },
  {
    id: 'seed-stoneware-mugs',
    slug: 'stoneware-mugs-set-of-four',
    name: 'Stoneware Mugs, Set of Four',
    brand: 'Homeware & Co',
    category: 'tableware',
    family: 'stoneware',
    description:
      'Generous 350ml mugs with a handle big enough for a whole hand. Thick walls keep coffee hot noticeably longer than thin porcelain.',
    specs: ['350ml each', 'Set of four', 'Dishwasher and microwave safe'],
    care: ['Dishwasher safe'],
    inBox: ['4 mugs'],
    sizeLabel: '4 × 350ml',
    price: 28000,
    compareAt: 35000,
    stock: 38,
    imageUrl: null,
    accent: 'sage',
    featured: false,
    bestseller: true,
    rating: 4.8,
    reviewCount: 129,
  },

  // --------------------------------------------------------------- glassware
  {
    id: 'seed-tumblers',
    slug: 'ribbed-tumblers-set-of-six',
    name: 'Ribbed Tumblers, Set of Six',
    brand: 'Homeware & Co',
    category: 'glassware',
    family: 'glass',
    description:
      'Vertical ribbing that catches the light and, more usefully, stops a wet glass sliding out of your hand. Heavy base, 350ml, stacks safely.',
    specs: ['350ml each', 'Set of six', 'Tempered glass', 'Dishwasher safe'],
    care: ['Dishwasher safe', 'Avoid sudden temperature changes'],
    inBox: ['6 tumblers'],
    sizeLabel: '6 × 350ml',
    price: 24500,
    compareAt: 32000,
    stock: 42,
    imageUrl: null,
    accent: 'sage',
    featured: true,
    bestseller: true,
    rating: 4.8,
    reviewCount: 156,
  },
  {
    id: 'seed-wine-glasses',
    slug: 'crystal-wine-glasses-set-of-four',
    name: 'Crystal Wine Glasses, Set of Four',
    brand: 'Homeware & Co',
    category: 'glassware',
    family: 'crystal',
    description:
      'Lead-free crystal with a pulled stem — no seam where the bowl meets the stem, which is what separates these from supermarket glasses. Thin rim, surprisingly durable.',
    specs: ['550ml bowl', 'Lead-free crystal', 'Pulled seamless stem', 'Dishwasher safe'],
    care: ['Dishwasher safe on a gentle cycle', 'Store upright, never on the rim'],
    inBox: ['4 wine glasses'],
    sizeLabel: '4 × 550ml',
    price: 38000,
    compareAt: null,
    stock: 23,
    imageUrl: null,
    accent: 'slate',
    featured: false,
    bestseller: false,
    rating: 4.9,
    reviewCount: 71,
  },
  {
    id: 'seed-water-carafe',
    slug: 'glass-water-carafe',
    name: 'Glass Water Carafe',
    brand: 'Homeware & Co',
    category: 'glassware',
    family: 'glass',
    description:
      'A 1.2 litre carafe with a snug wooden lid that doubles as a tumbler. Looks right on a dining table and keeps dust out of the water.',
    specs: ['1.2 litre', 'Borosilicate glass', 'Acacia lid that doubles as a cup'],
    care: ['Glass is dishwasher safe', 'Wash the wooden lid by hand'],
    inBox: ['Carafe', 'Acacia lid'],
    sizeLabel: '1.2L',
    price: 21500,
    compareAt: 27000,
    stock: 29,
    imageUrl: null,
    accent: 'sand',
    featured: false,
    bestseller: false,
    rating: 4.7,
    reviewCount: 58,
  },

  // ----------------------------------------------------------------- storage
  {
    id: 'seed-glass-canisters',
    slug: 'airtight-glass-canisters-set-of-three',
    name: 'Airtight Glass Canisters, Set of Three',
    brand: 'Homeware & Co',
    category: 'storage',
    family: 'glass',
    description:
      'Bamboo lids with a silicone gasket that genuinely seals — garri, rice and beans stay dry through the rainy season. Glass so you can see what is running low.',
    specs: ['1.5L, 1.0L and 0.7L', 'Borosilicate glass', 'Bamboo lid with silicone seal', 'Stackable'],
    care: ['Glass is dishwasher safe', 'Wash bamboo lids by hand'],
    inBox: ['3 canisters with lids'],
    sizeLabel: '3 sizes',
    price: 32000,
    compareAt: 41000,
    stock: 34,
    imageUrl: null,
    accent: 'sand',
    featured: true,
    bestseller: true,
    rating: 4.9,
    reviewCount: 201,
  },
  {
    id: 'seed-mixing-bowls',
    slug: 'stainless-mixing-bowls-set-of-five',
    name: 'Stainless Mixing Bowls, Set of Five',
    brand: 'Homeware & Co',
    category: 'storage',
    family: 'stainless steel',
    description:
      'Five nesting bowls from 0.7 to 5 litres with silicone bases that stop them spinning while you whisk. They nest down to the footprint of the largest.',
    specs: ['0.7L to 5L, five bowls', 'Stainless steel with non-slip base', 'Nesting design', 'Dishwasher safe'],
    care: ['Dishwasher safe'],
    inBox: ['5 nesting bowls'],
    sizeLabel: '5 bowls',
    price: 34500,
    compareAt: null,
    stock: 26,
    imageUrl: null,
    accent: 'slate',
    featured: false,
    bestseller: false,
    rating: 4.8,
    reviewCount: 94,
  },
  {
    id: 'seed-food-containers',
    slug: 'borosilicate-food-containers-set-of-six',
    name: 'Borosilicate Food Containers, Set of Six',
    brand: 'Homeware & Co',
    category: 'storage',
    family: 'glass',
    description:
      'Oven-to-fridge glass containers with locking lids. Reheat straight in the container, and glass does not stain or hold the smell of last night’s stew the way plastic does.',
    specs: ['6 containers with lids', 'Borosilicate glass, oven safe to 400°C', 'Four-clip locking lids with seal', 'Freezer and microwave safe'],
    care: ['Containers are dishwasher safe', 'Remove lids before oven use'],
    inBox: ['6 containers', '6 locking lids'],
    sizeLabel: '6 pieces',
    price: 36500,
    compareAt: 45000,
    stock: 30,
    imageUrl: null,
    accent: 'sage',
    featured: false,
    bestseller: true,
    rating: 4.8,
    reviewCount: 148,
  },

  // ---------------------------------------------------------------- textiles
  {
    id: 'seed-linen-apron',
    slug: 'washed-linen-apron',
    name: 'Washed Linen Apron',
    brand: 'Homeware & Co',
    category: 'textiles',
    family: 'linen',
    description:
      'Stonewashed linen that starts soft instead of stiff, with a cross-back strap so the weight sits on your shoulders rather than your neck. Deep double pocket.',
    specs: ['100% stonewashed linen', 'Cross-back straps, one size', 'Double front pocket', 'Machine washable'],
    care: ['Machine wash cold', 'Line dry — it softens with every wash'],
    inBox: ['Linen apron'],
    sizeLabel: 'One size',
    price: 22000,
    compareAt: 28000,
    stock: 36,
    imageUrl: null,
    accent: 'clay',
    featured: true,
    bestseller: false,
    rating: 4.8,
    reviewCount: 87,
  },
  {
    id: 'seed-waffle-tea-towels',
    slug: 'waffle-tea-towels-set-of-four',
    name: 'Waffle Tea Towels, Set of Four',
    brand: 'Homeware & Co',
    category: 'textiles',
    family: 'cotton',
    description:
      'Waffle weave cotton, which holds far more water than flat weave and dries much faster. Four to a set so there is always a clean one.',
    specs: ['50 × 70cm each', '100% cotton waffle weave', 'Set of four', 'Hanging loop'],
    care: ['Machine wash warm', 'Tumble dry low'],
    inBox: ['4 tea towels'],
    sizeLabel: '4 towels',
    price: 14500,
    compareAt: null,
    stock: 48,
    imageUrl: null,
    accent: 'sage',
    featured: false,
    bestseller: true,
    rating: 4.7,
    reviewCount: 112,
  },
  {
    id: 'seed-oven-mitt-set',
    slug: 'quilted-oven-mitt-and-pot-holder',
    name: 'Quilted Oven Mitt & Pot Holder',
    brand: 'Homeware & Co',
    category: 'textiles',
    family: 'cotton',
    description:
      'Thick quilted cotton rated to 220°C, long enough on the cuff to protect your wrist reaching into a hot oven — the part cheap mitts always get wrong.',
    specs: ['Heat resistant to 220°C', 'Extended cuff', 'Quilted cotton with cotton batting', 'Machine washable'],
    care: ['Machine wash warm', 'Do not bleach'],
    inBox: ['1 oven mitt', '1 pot holder'],
    sizeLabel: '2 pieces',
    price: 12500,
    compareAt: 16000,
    stock: 44,
    imageUrl: null,
    accent: 'clay',
    featured: false,
    bestseller: false,
    rating: 4.7,
    reviewCount: 76,
  },
  {
    id: 'seed-table-runner',
    slug: 'linen-table-runner',
    name: 'Linen Table Runner',
    brand: 'Homeware & Co',
    category: 'textiles',
    family: 'linen',
    description:
      'A 200cm runner in the same washed linen as the apron. Dresses a plain table instantly and takes a hot dish without a mat.',
    specs: ['200 × 40cm', '100% washed linen', 'Mitred corners'],
    care: ['Machine wash cold', 'Warm iron if you want it crisp'],
    inBox: ['Table runner'],
    sizeLabel: '200 × 40cm',
    price: 18500,
    compareAt: null,
    stock: 27,
    imageUrl: null,
    accent: 'sand',
    featured: false,
    bestseller: false,
    rating: 4.6,
    reviewCount: 49,
  },
  {
    id: 'seed-copper-utensils',
    slug: 'copper-utensil-set-of-five',
    name: 'Copper Utensil Set of Five',
    brand: 'Homeware & Co',
    category: 'storage',
    family: 'copper',
    description:
      'Slotted turner, ladle, serving spoon, skimmer and pasta server in copper-finished stainless with a matching stand. Heavy handles that do not bend under a pot of beans.',
    specs: ['5 utensils plus stand', 'Copper-finished stainless steel', 'Hanging loops'],
    care: ['Hand wash to protect the finish', 'Dry immediately'],
    inBox: ['5 utensils', 'Standing holder'],
    sizeLabel: '5 pieces',
    price: 29500,
    compareAt: 38000,
    stock: 25,
    imageUrl: null,
    accent: 'copper',
    featured: true,
    bestseller: false,
    rating: 4.7,
    reviewCount: 68,
  },
  ] as SeedProduct[]
).map((p) => ({ ...p, artShape: null }));

export const CATALOG_BY_SLUG = new Map(CATALOG.map((p) => [p.slug, p]));
